# config/s3.yml
development:
  access_key_id: AKIAI3SFXWVKKD5YV3FQ
  secret_access_key: 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
  bucket: verifier




production:
  access_key_id: AKIAI3SFXWVKKD5YV3FQ
  secret_access_key: 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
  bucket: verifier




 